apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-ipf4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-ipf4
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-ipf4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-ipf4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-ipf4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fuhc-tenant/nodejs-users/simple-nodejs-app-ipf4@sha256:267a3eef057f280c44d282a5f1561319510f2fd9f782f416027127c212fb87ef
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
